management:
  endpoints.web:
    base-path: /management
    exposure.include: '*'
  server.port: 9090

server:
  connection-timeout: 30000ms
  port: 8081
  servlet.context-path: /

logging:
  path: ./
  file: st.log
  #max-size: 10M
  #max-history: 1

spring:
  data:
    mongodb:

      database: studentService
      host: localhost
      port: 27017
  datasource:
    url: jdbc:mysql:localhost:3306
    driver-class-name: com.mysql.jdbc.Driver
    username: studentService
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml

master:
  name: EvanDevyml
  sex: nv
  subject: chi