CREATE DATABASE IF NOT EXISTS `studentService`;

CREATE TABLE IF NOT EXISTS `t_student` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `age` INT(255) DEFAULT NULL,
  `sex` VARCHAR(255) DEFAULT NULL,
  `phone` INT(255) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `citation_count` INT(255) DEFAULT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `t_student_score` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(255) DEFAULT NULL,
  `student_id` INT(255) DEFAULT NULL,
  `subject_score` INT(255),
  PRIMARY KEY  (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1;

